### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by 1nteg3r** [Nocture-Insight/Kernel-Dexterion#2]
So im getting an error whenever I launch it from Microsft Visual Redistruible saying Debug Error Abort(); has been called.

1. I have managed to build the driver and the UM cheat, ive modified the cheat lightly optimizng it with multithreaded processing to improve performance, adding a few features, but I got the same error while running it both fresh from github and my own version.
2. I successfuly map and build the driver with no error using kdmapper.

How can I fix this? Am I the only one experiencing this ?

**Comment by Skwrr** [comment]
Hello! Sorry for the late response (I'm currently very busy with school and other stuff). We don't know if you're the only one experiencing this as there's no other reports of this issue. Try updating your Windows version or change your OS (MiniOS 10 is working atm)
